site_name: 'flightpricetracker'
repo_url: https://github.com/ShawnDen-coder/flightpricetracker
site_url: https://ShawnDen-coder.github.io/flightpricetracker
site_description: An intelligent flight price monitoring system powered by Amadeus API that helps you never miss the best deals on airfare.
site_author: Shawn Deng
edit_uri: edit/main/docs/
repo_name: ShawnDen-coder/flightpricetracker
copyright: Maintained by <a href="https://github.com/ShawnDen-coder">ShawnDen-coder</a>.

nav:
  - Home: index.md
  - API Reference: reference/

plugins:
  - search
  - gen-files:
      scripts:
        - docs/gen_ref_pages.py
        - docs/gen_home_pages.py
  - literate-nav:
      nav_file: SUMMARY.md
  - mkdocstrings:
      handlers:
        python:
          paths: ["flightpricetracker"]
          options:
            docstring_style: "google"
            show_source: true
            show_root_heading: true
            show_signature_annotations: true
            separate_signature: true
            show_bases: true
            merge_init_into_class: true
            docstring_section_style: "spacy"
            show_if_no_docstring: false

theme:
  name: material
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - navigation.sections
    - navigation.expand
    - navigation.indexes
    - navigation.top
    - search.highlight
    - search.share
    - search.suggest
    - content.code.copy

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - tables
  - toc:
      permalink: true

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/ShawnDen-coder/flightpricetracker
    - icon: fontawesome/brands/python
      link: https://pypi.org/project/flightpricetracker
